version: '3.8'

services:
    db:
        image: mongo
        environment:
            - MONGO_DATA_DIR=/usr/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - ./data/db:/usr/data/db
        command: mongod --logpath=/dev/null # --quiet
        ports:
            - "27017:27017"
    backend:
        build: ./api
        volumes:
            - .:/code
        ports:
            - "5000:5000"
        depends_on:
            - db
        environment:
            - ENV=development
            - PORT=5000
            - DB=mongodb://db:27017/todoDev
            - JWT_SECRET_KEY=kjklsadfjioji234238472h34jhkb234jk09324kjnkj
